# Generated by Django 2.0.4 on 2018-04-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navfile',
            name='InfoDate',
            field=models.DateField(auto_created=True, auto_now_add=True, primary_key=True, serialize=False, verbose_name='口径日期'),
        ),
    ]
