# Generated by Django 2.0.4 on 2018-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadedDateTime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='上传时间')),
                ('File', models.FileField(upload_to='Pl\\Branch', verbose_name='数据文件')),
            ],
            options={
                'verbose_name': '经营机构批量导入',
                'verbose_name_plural': '经营机构批量导入',
            },
        ),
    ]
