# Generated by Django 2.0.4 on 2018-04-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navfile',
            name='InfoDate',
            field=models.DateField(verbose_name='口径日期'),
        ),
    ]
