# Generated by Django 2.0.4 on 2018-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S2', '0002_auto_20180423_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navfile',
            name='InfoDate',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='口径日期'),
        ),
        migrations.AlterField(
            model_name='navfile',
            name='UploadedDateTime',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='上传时间'),
        ),
    ]
