# Generated by Django 2.0.4 on 2018-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S2', '0002_auto_20180423_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navfile',
            name='File',
            field=models.FileField(upload_to='excelfiles', verbose_name='数据文件'),
        ),
    ]
